topics_list = [
    # Artificial Intelligence
    "How AI is reshaping the software engineer's role in 2026",
    "RAG vs Fine-tuning: a practical guide to choosing the right approach",
    "Common mistakes when deploying AI applications to production",
    "How to evaluate the output quality of an LLM in your project",
    "What AI still cannot replace in a skilled software engineer",
    "Top AI tools every developer should try right now",
    "How to build a simple yet powerful AI Agent without overcomplicating it",
    "Prompt Engineering vs Context Engineering: what actually matters",
    "Why most AI projects fail before they ever launch",
    "Using AI to speed up Code Review in your team",

    # Databases
    "PostgreSQL vs MongoDB: when to choose each and why",
    "Top 5 database design mistakes developers make and how to avoid them",
    "How to fix a slow query in 3 practical steps",
    "Index vs Composite Index: the practical difference and when to use each",
    "Connection Pooling: why every production app needs it",
    "Database Sharding explained: when you need it and how to start",
    "How to design a flexible schema that survives future changes",
    "ACID vs BASE: choosing the right model for your project",
    "Best backup strategies for production databases",
    "How to read and optimize a Query Execution Plan",

    # Software Engineering
    "SOLID principles explained with real code examples",
    "How to write code that others can understand 6 months later",
    "Architecture vs Design Pattern: when does the choice actually matter",
    "Microservices: when they are the solution and when they are the problem",
    "What to actually look for in an effective Code Review",
    "Technical Debt: how to measure it and convince your team to fix it",
    "How to design an API that lasts for years without breaking changes",
    "Event-Driven Architecture: when does your project actually need it",
    "Monorepo vs Polyrepo: the tradeoffs from real experience",
    "How to build a Fault Tolerant system from the ground up",

    # DevOps & Cloud
    "CI/CD Pipeline: the essential steps every serious project needs",
    "Docker explained: from zero to production in 5 core concepts",
    "How to cut Cloud costs without hurting performance",
    "Kubernetes: when does it become a necessity rather than a luxury",
    "The Observability trio: Logs, Metrics, and Traces",
    "Infrastructure as Code: why you should start today",
    "How to build a zero-downtime Deployment Strategy",
    "Blue-Green Deployment: the secret that saves you from disasters",
    "GitHub Actions: building a professional Workflow from scratch",
    "How to secure your API Gateway in a production environment",

    # Python
    "Modern Python features that will change how you write code",
    "AsyncIO explained: when to use it and when to avoid it",
    "How to write Unit Tests that actually protect your codebase",
    "Type Hints in Python: from optional to essential",
    "Generator vs List: why the choice matters for memory efficiency",
    "Pydantic: how to protect your data from the very first line of code",
    "Best Python libraries for automating repetitive tasks",
    "Python dataclasses vs Pydantic: which one should you use",

    # Career & Soft Skills
    "How to read documentation efficiently and save hours of your time",
    "Debugging mastery: how to find the bug in half the time",
    "How to evaluate a tech job offer intelligently before accepting",
    "System Design interviews: how I approach solving complex problems",
    "From developer to Tech Lead: skills no coding tutorial teaches you",
    "How to build a technical portfolio that actually opens doors",
    "Open Source contribution: how to start and what you truly gain",
    "How to negotiate your tech salary with confidence",
    "The real difference between a fast developer and a mature one",
    "How to stay current in a field that changes every 6 months",

    # Strategy & Architecture
    "Why I recommend every developer build a Side Project",
    "How to analyze project requirements before writing a single line of code",
    "Startup Tech Stack vs Enterprise Tech Stack: key differences",
    "When it is right for a developer to push back on requirements",
    "How to measure your engineering team's performance with real metrics",
    "Build vs Buy: how to make the right decision for your project",
    "How to write Technical Documentation that people actually read",
    "The C4 Model: how to draw system architecture with clarity",
    "How to run a productive technical retrospective with your team",
    "Scaling a backend from 1000 to 1 million users: what actually changes",
]
